dictionaries = ["de", "en_us"]
words = [
	"astro",
	"backreference",
	"behaviour",
	"breakline",
	"claude",
	"CLI",
	"codebases",
	"codebook",
	"codemod",
	"commitlint",
	"cspell",
	"czg",
	"ecma",
	"esm",
	"esnext",
	"gitbutler",
	"github",
	"innerhtml",
	"isnan",
	"kodiak",
	"linebreak",
	"lookarounds",
	"mheob",
	"nextjs",
	"nocheck",
	"nodenext",
	"nonconstructor",
	"nonwords",
	"nuxt",
	"NVIM",
	"oneline",
	"optimisation",
	"oxc",
	"oxfmt",
	"oxlint",
	"Parens",
	"pcss",
	"pnpm",
	"polyfillio",
	"preconfigured",
	"readdir",
	"rulelevels",
	"ruleset",
	"setstate",
	"smol",
	"tailwindcss",
	"textnodes",
	"trivago",
	"trunc",
	"tsdown",
	"tsgo",
	"tsgolint",
	"tsup",
	"turborepo",
	"unicode",
	"unocss",
	"vitepress",
	"vuejs",
	"worklet",
	"yoda",
]

