packages:
  - packages/*
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
catalogMode: prefer
catalog:
  "@antfu/install-pkg": ^1.1.0
  "@changesets/cli": ^2.29.4
  "@clack/prompts": ^0.11.0
  "@commitlint/cli": ^19.8.1
  "@cspell/dict-de-de": ^4.1.0
  "@eslint-community/eslint-plugin-eslint-comments": ^4.5.0
  "@eslint-react/eslint-plugin": ^1.51.3
  "@eslint/config-inspector": ^1.1.0
  "@mheob/changeset-changelog": ^3.0.2
  "@types/node": ^22.15.30
  "@types/yargs": ^17.0.33
  "@typescript-eslint/eslint-plugin": ^8.33.1
  "@typescript-eslint/parser": ^8.33.1
  "@vitest/eslint-plugin": ^1.2.1
  ansis: ^4.1.0
  astro-eslint-parser: ^1.2.2
  cac: ^6.7.14
  commitizen: ^4.3.1
  cspell: ^9.0.2
  cz-git: ^1.11.1
  eslint: ^9.28.0
  eslint-config-flat-gitignore: ^2.1.0
  eslint-config-next: ^15.3.3
  eslint-config-prettier: ^10.1.5
  eslint-flat-config-utils: ^2.1.0
  eslint-merge-processors: ^2.0.0
  eslint-plugin-antfu: ^3.1.1
  eslint-plugin-astro: ^1.3.1
  eslint-plugin-command: ^3.2.1
  eslint-plugin-jsdoc: ^50.7.1
  eslint-plugin-jsonc: ^2.20.1
  eslint-plugin-markdown: ^5.1.0
  eslint-plugin-n: ^17.19.0
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.14.0
  eslint-plugin-prettier: ^5.4.1
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-regexp: ^2.9.0
  eslint-plugin-svelte: ^3.9.1
  eslint-plugin-toml: ^0.12.0
  eslint-plugin-unicorn: ^59.0.1
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vue: ^10.2.0
  eslint-plugin-yml: ^1.18.0
  eslint-typegen: ^2.2.0
  globals: ^16.2.0
  husky: ^9.1.7
  jsonc-eslint-parser: ^2.4.0
  lint-staged: ^16.1.0
  local-pkg: ^1.1.1
  parse-gitignore: ^2.0.0
  prettier: ^3.5.3
  prettier-plugin-astro: ^0.14.1
  rimraf: ^6.0.1
  svelte: ^5.33.18
  svelte-eslint-parser: ^1.2.0
  toml-eslint-parser: ^0.10.0
  ts-node: ^10.9.2
  tsdown: ^0.12.7
  tsx: ^4.19.4
  turbo: ^2.5.4
  typescript: ^5.8.3
  vue-eslint-parser: ^10.1.3
  yaml: ^2.8.0
  yaml-eslint-parser: ^1.3.0
  yargs: ^18.0.0
