packages:
  - packages/*

catalogMode: prefer

catalog:
  "@antfu/install-pkg": ^1.1.0
  "@changesets/cli": ^2.29.8
  "@clack/prompts": ^0.11.0
  "@commitlint/cli": ^20.2.0
  "@cspell/dict-de-de": ^4.1.2
  "@eslint-community/eslint-plugin-eslint-comments": ^4.5.0
  "@eslint-react/eslint-plugin": ^2.3.12
  "@eslint/config-inspector": ^1.4.2
  "@eslint/markdown": ^7.5.1
  "@mheob/changeset-changelog": ^3.0.2
  "@next/eslint-plugin-next": ^16.0.7
  "@stylistic/eslint-plugin": ^5.6.1
  "@types/node": ^24.10.1
  "@types/yargs": ^17.0.35
  "@typescript-eslint/eslint-plugin": ^8.48.1
  "@typescript-eslint/parser": ^8.48.1
  "@vitest/eslint-plugin": ^1.5.1
  ansis: ^4.2.0
  astro-eslint-parser: ^1.2.2
  cac: ^6.7.14
  commitizen: ^4.3.1
  cspell: ^9.4.0
  cz-git: ^1.12.0
  eslint: ^9.39.1
  eslint-config-flat-gitignore: ^2.1.0
  eslint-config-next: ^16.0.7
  eslint-config-prettier: ^10.1.8
  eslint-flat-config-utils: ^2.1.4
  eslint-merge-processors: ^2.0.0
  eslint-plugin-antfu: ^3.1.1
  eslint-plugin-astro: ^1.5.0
  eslint-plugin-command: ^3.3.1
  eslint-plugin-jsdoc: ^61.4.1
  eslint-plugin-jsonc: ^2.21.0
  eslint-plugin-n: ^17.23.1
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.15.1
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.24
  eslint-plugin-regexp: ^2.10.0
  eslint-plugin-svelte: ^3.13.1
  eslint-plugin-toml: ^0.12.0
  eslint-plugin-unicorn: ^62.0.0
  eslint-plugin-unused-imports: ^4.3.0
  eslint-plugin-vue: ^10.6.2
  eslint-plugin-yml: ^1.19.0
  eslint-typegen: ^2.3.0
  globals: ^16.5.0
  husky: ^9.1.7
  jsonc-eslint-parser: ^2.4.1
  lint-staged: ^16.2.7
  local-pkg: ^1.1.2
  parse-gitignore: ^2.0.0
  prettier: ^3.7.4
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-toml: 2.0.6
  rimraf: ^6.1.2
  svelte: ^5.45.6
  svelte-eslint-parser: ^1.4.1
  toml-eslint-parser: ^0.10.0
  ts-node: ^10.9.2
  tsdown: ^0.17.0
  tsx: ^4.21.0
  turbo: ^2.6.3
  typescript: ^5.9.3
  vue-eslint-parser: ^10.2.0
  yaml: ^2.8.2
  yaml-eslint-parser: ^1.3.2
  yargs: ^18.0.0
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
