import { defineConfig } from 'oxlint';

export const baseConfig = defineConfig({
	plugins: ['eslint', 'node', 'jsdoc', 'import', 'oxc', 'typescript', 'unicorn'],

	categories: {
		correctness: 'error',
		nursery: 'warn',
		pedantic: 'warn',
		perf: 'warn',
		restriction: 'warn',
		style: 'warn',
		suspicious: 'error',
	},

	env: {
		builtin: true,
		browser: true,
		es2026: true,
		node: true,
	},

	globals: {
		AudioWorkletGlobalScope: 'readonly',
		AudioWorkletProcessor: 'readonly',
		currentFrame: 'readonly',
		currentTime: 'readonly',
		registerProcessor: 'readonly',
		sampleRate: 'readonly',
		WorkletGlobalScope: 'readonly',
	},

	rules: {
		// ESLint rules
		'eslint/accessor-pairs': 'error',
		'eslint/array-callback-return': 'error',
		'eslint/block-scoped-var': 'error',
		'eslint/default-case-last': 'error',
		'eslint/eqeqeq': ['error', 'smart'],
		'eslint/new-cap': ['error', { capIsNew: false }],
		'eslint/no-alert': 'error',
		'eslint/no-array-constructor': 'error',
		'eslint/no-case-declarations': 'error',
		'eslint/no-console': ['warn', { allow: ['error', 'info', 'warn'] }],
		'eslint/no-else-return': 'error',
		'eslint/no-empty': 'error',
		'eslint/no-fallthrough': 'error',
		'eslint/no-implicit-coercion': ['error', { allow: ['+', '~'] }],
		'eslint/no-labels': 'error',
		'eslint/no-lone-blocks': 'error',
		'eslint/no-lonely-if': 'error',
		'eslint/no-multi-str': 'error',
		'eslint/no-new': 'error',
		'eslint/no-new-func': 'error',
		'eslint/no-new-wrappers': 'error',
		'eslint/no-proto': 'error',
		'eslint/no-prototype-builtins': 'error',
		'eslint/no-redeclare': ['error', { builtinGlobals: false }],
		'eslint/no-regex-spaces': 'error',
		'eslint/no-restricted-globals': [
			'error',
			{ message: 'Use `globalThis` instead.', name: 'global' },
			{ message: 'Use `globalThis` instead.', name: 'self' },
		],
		'eslint/no-self-compare': 'error',
		'eslint/no-sequences': 'error',
		'eslint/no-template-curly-in-string': 'error',
		'eslint/no-unneeded-ternary': ['error', { defaultAssignment: false }],
		'eslint/no-useless-computed-key': 'error',
		'eslint/no-useless-return': 'error',
		'eslint/no-var': 'error',
		'eslint/prefer-rest-params': 'error',
		'eslint/prefer-template': 'error',
		'eslint/symbol-description': 'error',
		'eslint/yoda': 'error',

		// Import rules
		'import/default': 'error',
		'import/first': 'error',
		'import/namespace': 'error',
		'import/no-duplicates': 'error',
		'import/no-mutable-exports': 'error',
		'import/no-named-default': 'error',
		'import/no-self-import': 'error',
		'import/no-webpack-loader-syntax': 'error',

		// JSDoc rules
		'jsdoc/check-access': 'warn',
		'jsdoc/check-property-names': 'warn',
		'jsdoc/check-tag-names': 'warn',
		'jsdoc/empty-tags': 'warn',
		'jsdoc/implements-on-classes': 'warn',
		'jsdoc/no-defaults': 'warn',
		'jsdoc/require-param': 'warn',
		'jsdoc/require-param-description': 'warn',
		'jsdoc/require-param-name': 'warn',
		'jsdoc/require-property': 'warn',
		'jsdoc/require-property-description': 'warn',
		'jsdoc/require-property-name': 'warn',
		'jsdoc/require-returns': 'warn',
		'jsdoc/require-returns-description': 'warn',
		'jsdoc/require-yields': 'warn',

		// Node rules
		'node/no-exports-assign': 'error',
		'node/no-new-require': 'error',

		// TypeScript rules
		'typescript/ban-ts-comment': ['error', { 'ts-ignore': 'allow-with-description' }],
		'typescript/consistent-type-definitions': ['error', 'interface'],
		'typescript/consistent-type-imports': 'error',
		'typescript/explicit-function-return-type': ['error', { allowExpressions: true }],
		'typescript/no-empty-object-type': 'error',
		'typescript/no-explicit-any': 'warn',
		'typescript/no-import-type-side-effects': 'error',
		'typescript/no-namespace': 'error',
		'typescript/no-non-null-asserted-nullish-coalescing': 'error',
		'typescript/no-non-null-assertion': 'warn',
		'typescript/no-require-imports': 'error',
		'typescript/no-restricted-types': 'error',
		'typescript/no-unnecessary-type-constraint': 'error',
		'typescript/no-unsafe-function-type': 'error',
		'typescript/only-throw-error': 'error',
		'typescript/prefer-literal-enum-member': 'error',
		'typescript/prefer-optional-chain': 'error',
		'typescript/prefer-promise-reject-errors': 'error',

		// Unicorn rules
		'unicorn/catch-error-name': 'error',
		'unicorn/consistent-assert': 'error',
		'unicorn/consistent-date-clone': 'error',
		'unicorn/consistent-empty-array-spread': 'error',
		'unicorn/consistent-existence-index-check': 'error',
		'unicorn/consistent-function-scoping': 'error',
		'unicorn/error-message': 'error',
		'unicorn/escape-case': 'error',
		'unicorn/explicit-length-check': 'error',
		'unicorn/new-for-builtins': 'error',
		'unicorn/no-accessor-recursion': 'error',
		'unicorn/no-anonymous-default-export': 'error',
		'unicorn/no-array-callback-reference': 'error',
		'unicorn/no-array-for-each': 'error',
		'unicorn/no-array-method-this-argument': 'error',
		'unicorn/no-array-reverse': 'error',
		'unicorn/no-array-sort': 'error',
		'unicorn/no-await-expression-member': 'error',
		'unicorn/no-console-spaces': 'error',
		'unicorn/no-document-cookie': 'error',
		'unicorn/no-hex-escape': 'error',
		'unicorn/no-immediate-mutation': 'error',
		'unicorn/no-instanceof-builtins': 'error',
		'unicorn/no-invalid-remove-event-listener': 'error',
		'unicorn/no-lonely-if': 'error',
		'unicorn/no-magic-array-flat-depth': 'error',
		'unicorn/no-negation-in-equality-check': 'error',
		'unicorn/no-new-buffer': 'error',
		'unicorn/no-object-as-default-parameter': 'error',
		'unicorn/no-process-exit': 'error',
		'unicorn/no-static-only-class': 'error',
		'unicorn/no-this-assignment': 'error',
		'unicorn/no-typeof-undefined': 'error',
		'unicorn/no-unnecessary-array-flat-depth': 'error',
		'unicorn/no-unnecessary-array-splice-count': 'error',
		'unicorn/no-unnecessary-slice-end': 'error',
		'unicorn/no-unreadable-array-destructuring': 'error',
		'unicorn/no-unreadable-iife': 'error',
		'unicorn/no-useless-collection-argument': 'error',
		'unicorn/no-useless-error-capture-stack-trace': 'error',
		'unicorn/no-useless-promise-resolve-reject': 'error',
		'unicorn/no-useless-spread': 'error',
		'unicorn/no-useless-switch-case': 'error',
		'unicorn/no-useless-undefined': 'error',
		'unicorn/no-zero-fractions': 'error',
		'unicorn/numeric-separators-style': 'error',
		'unicorn/prefer-add-event-listener': 'error',
		'unicorn/prefer-array-find': 'error',
		'unicorn/prefer-array-flat': 'error',
		'unicorn/prefer-array-flat-map': 'error',
		'unicorn/prefer-array-index-of': 'error',
		'unicorn/prefer-array-some': 'error',
		'unicorn/prefer-at': 'error',
		'unicorn/prefer-bigint-literals': 'error',
		'unicorn/prefer-blob-reading-methods': 'error',
		'unicorn/prefer-class-fields': 'error',
		'unicorn/prefer-classlist-toggle': 'error',
		'unicorn/prefer-code-point': 'error',
		'unicorn/prefer-date-now': 'error',
		'unicorn/prefer-default-parameters': 'error',
		'unicorn/prefer-dom-node-append': 'error',
		'unicorn/prefer-dom-node-dataset': 'error',
		'unicorn/prefer-dom-node-remove': 'error',
		'unicorn/prefer-dom-node-text-content': 'error',
		'unicorn/prefer-event-target': 'error',
		'unicorn/prefer-global-this': 'error',
		'unicorn/prefer-includes': 'error',
		'unicorn/prefer-keyboard-event-key': 'error',
		'unicorn/prefer-logical-operator-over-ternary': 'error',
		'unicorn/prefer-math-min-max': 'error',
		'unicorn/prefer-math-trunc': 'error',
		'unicorn/prefer-modern-dom-apis': 'error',
		'unicorn/prefer-modern-math-apis': 'error',
		'unicorn/prefer-native-coercion-functions': 'error',
		'unicorn/prefer-negative-index': 'error',
		'unicorn/prefer-node-protocol': 'error',
		'unicorn/prefer-number-properties': 'error',
		'unicorn/prefer-object-from-entries': 'error',
		'unicorn/prefer-optional-catch-binding': 'error',
		'unicorn/prefer-prototype-methods': 'error',
		'unicorn/prefer-query-selector': 'error',
		'unicorn/prefer-reflect-apply': 'error',
		'unicorn/prefer-regexp-test': 'error',
		'unicorn/prefer-response-static-json': 'error',
		'unicorn/prefer-set-has': 'error',
		'unicorn/prefer-spread': 'error',
		'unicorn/prefer-string-raw': 'error',
		'unicorn/prefer-string-replace-all': 'error',
		'unicorn/prefer-string-slice': 'error',
		'unicorn/prefer-string-trim-start-end': 'error',
		'unicorn/prefer-structured-clone': 'error',
		'unicorn/prefer-top-level-await': 'error',
		'unicorn/prefer-type-error': 'error',
		'unicorn/require-array-join-separator': 'error',
		'unicorn/require-module-attributes': 'error',
		'unicorn/require-module-specifiers': 'error',
		'unicorn/require-number-to-fixed-digits-argument': 'error',
		'unicorn/switch-case-braces': 'error',
		'unicorn/text-encoding-identifier-case': 'error',
		'unicorn/throw-new-error': 'error',
	},

	overrides: [
		// CLI
		{
			files: ['**/cli.ts', '**/cli/**/*.ts'],
			rules: {
				'eslint/no-console': 'off',
				'unicorn/no-process-exit': 'off',
			},
		},

		// Config
		{
			files: ['**/.config.ts', '**/.config.*.ts'],
			rules: {
				'eslint/no-console': 'off',
				'typescript/explicit-function-return-type': 'off',
			},
		},

		// Markdown
		{
			files: [
				'**/*.md/**/*.ts',
				'**/*.md/**/*.js',
				'**/*.md/**/*.json',
				'**/*.md/**/*.json5',
				'**/*.md/**/*.jsonc',
			],
			rules: {
				'eslint/no-alert': 'off',
				'eslint/no-console': 'off',
				'eslint/no-labels': 'off',
				'eslint/no-lone-blocks': 'off',
				'eslint/no-redeclare': 'off',
				'eslint/no-unused-expressions': 'off',
				'eslint/no-unused-labels': 'off',
				'eslint/no-unused-vars': 'off',
				'eslint/unicode-bom': 'off',
				'typescript/await-thenable': 'off',
				'typescript/consistent-type-imports': 'off',
				'typescript/no-floating-promises': 'off',
				'typescript/no-for-in-array': 'off',
				'typescript/no-implied-eval': 'off',
				'typescript/no-misused-promises': 'off',
				'typescript/no-namespace': 'off',
				'typescript/no-require-imports': 'off',
				'typescript/no-unnecessary-type-assertion': 'off',
				'typescript/no-unsafe-argument': 'off',
				'typescript/no-unsafe-assignment': 'off',
				'typescript/no-unsafe-call': 'off',
				'typescript/no-unsafe-member-access': 'off',
				'typescript/no-unsafe-return': 'off',
				'typescript/no-var-requires': 'off',
				'typescript/restrict-plus-operands': 'off',
				'typescript/restrict-template-expressions': 'off',
				'typescript/unbound-method': 'off',
			},
		},

		// Scripts
		{
			files: ['**/scripts/**/*.ts'],
			rules: {
				'eslint/no-console': 'off',
				'typescript/explicit-function-return-type': 'off',
				'unicorn/no-process-exit': 'off',
			},
		},

		// Vitest rules
		{
			files: [
				'**/__tests__/**/*.ts',
				'**/__tests__/**/*.tsx',
				'**/*.spec.ts',
				'**/*.spec.tsx',
				'**/*.test.ts',
				'**/*.test.tsx',
				'**/*.bench.ts',
				'**/*.bench.tsx',
				'**/*.benchmark.ts',
				'**/*.benchmark.tsx',
			],
			plugins: ['vitest'],
			rules: {
				'vitest/consistent-each-for': 'error',
				'vitest/consistent-test-it': ['error', { fn: 'it', withinDescribe: 'it' }],
				'vitest/consistent-vitest-vi': 'error',
				'vitest/hoisted-apis-on-top': 'error',
				'vitest/no-conditional-tests': 'error',
				'vitest/no-identical-title': 'error',
				'vitest/no-import-node-test': 'error',
				'vitest/prefer-hooks-in-order': 'error',
				'vitest/prefer-lowercase-title': 'error',
				'vitest/require-local-test-context-for-concurrent-snapshots': 'error',
				'vitest/warn-todo': 'error',
			},
		},
	],
});
