import { defineConfig } from 'oxlint';

import { baseConfig } from './base';

export const baseJsConfig = defineConfig({
	extends: [baseConfig],

	jsPlugins: ['eslint-plugin-regexp'],

	overrides: [
		// Sort json files
		{
			files: ['**/*.json', '**/*.json5', '**/*.jsonc'],
			jsPlugins: ['eslint-plugin-jsonc'],
			rules: {
				'jsonc/no-bigint-literals': 'error',
				'jsonc/no-binary-expression': 'error',
				'jsonc/no-binary-numeric-literals': 'error',
				'jsonc/no-dupe-keys': 'error',
				'jsonc/no-escape-sequence-in-identifier': 'error',
				'jsonc/no-floating-decimal': 'error',
				'jsonc/no-hexadecimal-numeric-literals': 'error',
				'jsonc/no-infinity': 'error',
				'jsonc/no-multi-str': 'error',
				'jsonc/no-nan': 'error',
				'jsonc/no-number-props': 'error',
				'jsonc/no-numeric-separators': 'error',
				'jsonc/no-octal': 'error',
				'jsonc/no-octal-escape': 'error',
				'jsonc/no-octal-numeric-literals': 'error',
				'jsonc/no-parenthesized': 'error',
				'jsonc/no-plus-sign': 'error',
				'jsonc/no-regexp-literals': 'error',
				'jsonc/no-sparse-arrays': 'error',
				'jsonc/no-template-literals': 'error',
				'jsonc/no-undefined-value': 'error',
				'jsonc/no-unicode-codepoint-escapes': 'error',
				'jsonc/no-useless-escape': 'error',
				'jsonc/sort-array-values': [
					'error',
					{
						order: [{ order: { natural: true } }],
						pathPattern: '^$',
					},
				],
				'jsonc/sort-keys': [
					'error',
					{
						minKeys: 2,
						order: { natural: true, type: 'asc' },
						pathPattern: '^$',
					},
					{
						minKeys: 2,
						order: ['id', { order: { natural: true, type: 'asc' } }],
						pathPattern: '.*',
					},
				],
				'jsonc/space-unary-ops': 'error',
				'jsonc/valid-json-number': 'error',
				'jsonc/vue-custom-block/no-parsing-error': 'error',
			},
		},

		// Sort tsconfig.json
		{
			files: ['**/tsconfig.json', '**/tsconfig.*.json'],
			jsPlugins: ['eslint-plugin-jsonc'],
			rules: {
				'jsonc/sort-keys': [
					'error',
					{
						order: ['extends', 'compilerOptions', 'references', 'files', 'include', 'exclude'],
						pathPattern: '^$',
					},
					{
						order: [
							'incremental',
							'composite',
							'tsBuildInfoFile',
							'disableSourceOfProjectReferenceRedirect',
							'disableSolutionSearching',
							'disableReferencedProjectLoad',
							'target',
							'lib',
							'jsx',
							'libReplacement',
							'experimentalDecorators',
							'emitDecoratorMetadata',
							'jsxFactory',
							'jsxFragmentFactory',
							'jsxImportSource',
							'reactNamespace',
							'noLib',
							'useDefineForClassFields',
							'moduleDetection',
							'rootDir',
							'moduleResolution',
							'baseUrl',
							'paths',
							'rootDirs',
							'typeRoots',
							'types',
							'allowUmdGlobalAccess',
							'moduleSuffixes',
							'allowImportingTsExtensions',
							'rewriteRelativeImportExtensions',
							'resolvePackageJsonExports',
							'resolvePackageJsonImports',
							'customConditions',
							'noUncheckedSideEffectImports',
							'resolveJsonModule',
							'allowArbitraryExtensions',
							'noResolve',
							'allowJs',
							'checkJs',
							'maxNodeModuleJsDepth',
							'declaration',
							'declarationMap',
							'emitDeclarationOnly',
							'sourceMap',
							'inlineSourceMap',
							'noEmit',
							'outFile',
							'outDir',
							'removeComments',
							'importHelpers',
							'downlevelIteration',
							'sourceRoot',
							'mapRoot',
							'inlineSources',
							'emitBOM',
							'newLine',
							'stripInternal',
							'noEmitHelpers',
							'noEmitOnError',
							'preserveConstEnums',
							'declarationDir',
							'isolatedModules',
							'verbatimModuleSyntax',
							'isolatedDeclarations',
							'erasableSyntaxOnly',
							'allowSyntheticDefaultImports',
							'esModuleInterop',
							'preserveSymlinks',
							'forceConsistentCasingInFileNames',
							'strict',
							'noImplicitAny',
							'strictNullChecks',
							'strictFunctionTypes',
							'strictBindCallApply',
							'strictPropertyInitialization',
							'strictBuiltinIteratorReturn',
							'noImplicitThis',
							'useUnknownInCatchVariables',
							'alwaysStrict',
							'noUnusedLocals',
							'noUnusedParameters',
							'exactOptionalPropertyTypes',
							'noImplicitReturns',
							'noFallthroughCasesInSwitch',
							'noUncheckedIndexedAccess',
							'noImplicitOverride',
							'noPropertyAccessFromIndexSignature',
							'allowUnusedLabels',
							'allowUnreachableCode',
							'skipDefaultLibCheck',
							'skipLibCheck',
						],
						pathPattern: '^compilerOptions$',
					},
				],
			},
		},

		// YAML
		{
			files: ['**/*.yaml', '**/*.yml'],
			jsPlugins: ['eslint-plugin-yml'],
			rules: {
				'yml/block-mapping': 'error',
				'yml/block-sequence': 'error',
				'yml/no-empty-key': 'error',
				'yml/no-empty-sequence-entry': 'error',
				'yml/no-irregular-whitespace': 'error',
				'yml/plain-scalar': 'error',
				'yml/vue-custom-block/no-parsing-error': 'error',
			},
		},
	],

	rules: {
		// Regex
		'regexp/confusing-quantifier': 'warn',
		'regexp/control-character-escape': 'error',
		'regexp/match-any': 'error',
		'regexp/negation': 'error',
		'regexp/no-contradiction-with-assertion': 'error',
		'regexp/no-dupe-characters-character-class': 'error',
		'regexp/no-dupe-disjunctions': 'error',
		'regexp/no-empty-alternative': 'warn',
		'regexp/no-empty-capturing-group': 'error',
		'regexp/no-empty-character-class': 'error',
		'regexp/no-empty-group': 'error',
		'regexp/no-empty-lookarounds-assertion': 'error',
		'regexp/no-empty-string-literal': 'error',
		'regexp/no-escape-backspace': 'error',
		'regexp/no-extra-lookaround-assertions': 'error',
		'regexp/no-invalid-regexp': 'error',
		'regexp/no-invisible-character': 'error',
		'regexp/no-lazy-ends': 'warn',
		'regexp/no-legacy-features': 'error',
		'regexp/no-misleading-capturing-group': 'error',
		'regexp/no-misleading-unicode-character': 'error',
		'regexp/no-missing-g-flag': 'error',
		'regexp/no-non-standard-flag': 'error',
		'regexp/no-obscure-range': 'error',
		'regexp/no-optional-assertion': 'error',
		'regexp/no-potentially-useless-backreference': 'warn',
		'regexp/no-super-linear-backtracking': 'error',
		'regexp/no-trivially-nested-assertion': 'error',
		'regexp/no-trivially-nested-quantifier': 'error',
		'regexp/no-unused-capturing-group': 'error',
		'regexp/no-useless-assertions': 'error',
		'regexp/no-useless-backreference': 'error',
		'regexp/no-useless-character-class': 'error',
		'regexp/no-useless-dollar-replacements': 'error',
		'regexp/no-useless-escape': 'error',
		'regexp/no-useless-flag': 'warn',
		'regexp/no-useless-lazy': 'error',
		'regexp/no-useless-non-capturing-group': 'error',
		'regexp/no-useless-quantifier': 'error',
		'regexp/no-useless-range': 'error',
		'regexp/no-useless-set-operand': 'error',
		'regexp/no-useless-string-literal': 'error',
		'regexp/no-useless-two-nums-quantifier': 'error',
		'regexp/no-zero-quantifier': 'error',
		'regexp/optimal-lookaround-quantifier': 'warn',
		'regexp/optimal-quantifier-concatenation': 'error',
		'regexp/prefer-character-class': 'error',
		'regexp/prefer-d': 'error',
		'regexp/prefer-plus-quantifier': 'error',
		'regexp/prefer-predefined-assertion': 'error',
		'regexp/prefer-question-quantifier': 'error',
		'regexp/prefer-range': 'error',
		'regexp/prefer-set-operation': 'error',
		'regexp/prefer-star-quantifier': 'error',
		'regexp/prefer-unicode-codepoint-escapes': 'error',
		'regexp/prefer-w': 'error',
		'regexp/simplify-set-operations': 'error',
		'regexp/sort-flags': 'error',
		'regexp/strict': 'error',
		'regexp/use-ignore-case': 'error',
	},
});
