name: Check

on:
  pull_request:
  push:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe # v2
        with:
          bun-version-file: package.json

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build files
        run: bun run build

      - name: Lint files
        run: bun run lint
