on:
  pull_request:
  issue_comment:

jobs:
  pr_agent_job:
    name: Run pr agent on every pull request, respond to user comments

    permissions:
      issues: write
      pull-requests: write
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
