name: Release

on:
  push:
    paths:
      - ".changeset/**"
      - "packages/**"
      - bun.lock
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write # Required for OIDC
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ secrets.MACHINE_USER_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: .nvmrc

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version-file: package.json

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build files
        run: bun run build

      - name: Setup service bot git
        env:
          GIT_EMAIL: ${{ secrets.MACHINE_USER_EMAIL }}
          GIT_NAME: ${{ secrets.MACHINE_USER_NAME }}
        run: |
          git config --local user.email "${GIT_EMAIL}"
          git config --local user.name "${GIT_NAME}"

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore(release): bump version and deploy packages"
          title: "chore(release): bump version and deploy packages"
          setupGitUser: false
          publish: bun run release
          version: bun run version-packages
        env:
          GITHUB_TOKEN: ${{ secrets.MACHINE_USER_TOKEN }}
          NPM_CONFIG_PROVENANCE: "true"
